"do not touch" = true

[bookmarks]
  "m5sw22lone5c6l3bnvsxeltqn5wgy5lyfzrwc43bf5rgy33hf5wxsllhmvwws3tjfvrwc4dtovwgklljomwws3rnn5zge2lufztw22i=" = "Cool Informative Page"
  "m5sw22lone5c6l3cnfzgcytjor2g62boonww63boob2wely=" = "Bira Bittoh a good page "
  "m5sw22lone5c6l3dovyhaylkn5ss46dzpixxi5lun5zgsylmomxwgylqon2wyzk7or2xi33snfqwylthnvuq====" = "capsule tut"
  "m5sw22lone5c6l3emfzgw3tfonzwg33emuxhq6l2f5wgs3tvpaxws3ttorqwy3bnm5sw22lonewxgzlsozsxelthnvuq====" = "How to create a gemini capsule"
  m5sw22lone5c6l3gojuwk3ten4xg233oon2gk4rp = "🦉 Friendo dot monster"
  "m5sw22lone5c6l3gojuwk3ten4xg233oon2gk4rpmzzgkzk7onxwm5dxmfzgkx3jl5wgs23ffztw22i=" = "🦉 Book mark duh"
  "m5sw22lone5c6l3hmvws4y3iojuxg53fojss45llf4======" = "🐙 A good page by chris were"
  "m5sw22lone5c6l3hmvws4y3iojuxg53fojss45llf52hezlomr4xiylmnmxq====" = "Trendy Talk"
  m5sw22lone5c6l3hmvwws3tjfzrws4tdovwwy5lomfzc443qmfrwkl3en5rxgl3hmvwxizlyoqxgo3lj = "GemText Documentation"
  m5sw22lone5c6l3hmvwws3tjfzrws4tdovwwy5lomfzc443qmfrwkl3vonsxe4zpnnzgc2lmmv2gql3omv2w42lyf5swk4tjmuxtembrgixwy2loov4f6zdfonvxi33ql5ww6zdfojxf6z3unmxgo3lj = "Linux desktop comparision - modern GTK+ DEs"
  "m5sw22lone5c6l3hnvus4yloorxw42lpfzuxgly=" = "🚲 Antonio a programmer who started in 1993"
  "m5sw22lone5c6l3imv4gi43mfzrw6ltvnmxq====" = "🚀 HexDSL"
  m5sw22lone5c6l3ipfygk4tcn5zgkyjon5zgol3mn5ts6y3borswo33spexxizldnaxgo3lj = "🦜 oooo-tech blog"
  "m5sw22lone5c6l3jmruw63leojxxi5donfxgoltpojts65dfpb2hg===" = "idiomrottning texts or log"
  "m5sw22lone5c6l3jon3gc4tbnbygc4tbnvqwq23sonxgc2boonww63boob2wel3qn5zxi4y=" = "A good personal general of isvaraparamkrsnah"
  "m5sw22lone5c6l3ln54xklttobqwgzjpnnxxs5jpmnxw45dbmn2c4z3nne======" = "🐇 Koyu free hosting"
  "m5sw22lone5c6l3nmfzgo2lomfwgsyjonz2s63dpm4xtamzno5zgs5djnzts2ztpoiwxezlbmruw4zzom5wws===" = "Writing for Reading"
  "m5sw22lone5c6l3nmfzgo2lomfwgsyjonz2s65dpobuwg===" = "Good gemlog-1"
  "m5sw22lone5c6l3opf2ha5jomnxw2ly=" = "Nyptu's Capsule"
  "m5sw22lone5c6l3smfxgi33nfvyhe33kmvrxi4zonzsxily=" = "Random projects"
  "m5sw22lone5c6l3tnvxwyltqovrc6===" = "Smol Pub"
  m5sw22lone5c6l3wn5uwiy3sovuxgzlsfzxgyl3dn5xhiyldoqxgo3lj = "Void cruiser contact"
  "m5sw22lone5c6l3wn5uwiy3sovuxgzlsfzxgyl3porugk4ttfztw22i=" = "VoidCruiser Recommended Capsules"
